version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/standard.yml

# Using a manual jobs matrix to exclude PGSQL which has some legitimate failures
# https://travis-ci.com/github/symbiote/silverstripe-multivaluefield/jobs/451353312
jobs:
  fast_finish: true
  include:
    - php: 7.4
      env:
        - DB=MYSQL
        - PDO=1
        - REQUIRE_INSTALLER="4.x-dev"
        - PHPUNIT_TEST=1
        - PHPCS_TEST=1
    - php: 8.0
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="4.x-dev"
        - PHPUNIT_COVERAGE_TEST=1
    - php: 8.1.0
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="4.x-dev"
        - PHPUNIT_TEST=1
